### ISSUE TITLE
Not able to make the alter.

### ISSUE THREAD

**Issue by ZoruaW** [Exzotic5485/Reaper-Origin#1]
I followed the instructions and have everything I believe I'm supposed to have but when I take the scythe and hover over the cauldron and right-click it just swaps the items. Please help me fix this. Thanks!

**Comment by ZoruaW** [comment]
The things I have tried include, downloading from Github, downloading from discord, unzipping the one from Github, and unzipping the one from discord.

**Comment by Exzotic5485** [comment]
Hey! Are you using minecraft 1.17+ with origins 1.1.0+?
There is features that this origin uses that are only in 1.1.0+

**Comment by ZoruaW** [comment]
Yes, I use 1.17 1.0.3 is that why?

**Comment by Exzotic5485** [comment]
Yeah, that will be why. It uses the _origins:item_on_item_ power that is only in 1.1.0 and above.

**Comment by ZoruaW** [comment]
I'm downloading the newer version right now to try it.

**Comment by Exzotic5485** [comment]
Alright, let me know how it goes :)

**Comment by ZoruaW** [comment]
Ok so now sadly it keeps crashing. Even tried to update mob origins and extra origins.

**Comment by Exzotic5485** [comment]
Oh, server crashing or like your game wont load?

**Comment by ZoruaW** [comment]
Like when I click play on the launcher it gives me the game crashed error message.

**Comment by Exzotic5485** [comment]
Do you have optifine? Maybe theres an issue with origins and optifine.

**Comment by ZoruaW** [comment]
I could send it to you if you would like I'm never good at deciphering error messages.

**Comment by ZoruaW** [comment]
Oh I do maybe that will help.

**Comment by Exzotic5485** [comment]
Sure thing

**Comment by ZoruaW** [comment]
FINALLY, IT WORKS!

**Comment by ZoruaW** [comment]
Ok, I might just be stupid but with the diamond scythe how do you go into limbo?

**Comment by Exzotic5485** [comment]
Just right click while holding it

**Comment by ZoruaW** [comment]
Ok, thanks!
